clip:

  ingestion_mode: online_inference #Alternative batch_inference_job 

  datasets:
    datasets_path: ./data/datasets
    dataset_name: images_dataset
    dataset_description: Dataset for ImageSearch AISK
    dataset_source_file: ./data/datasets/source.json
    dataset_source_type: localMachine
   
  apps:
    clip_app_id: 6c14325a-1be7-4e48-b38f-19b33745fc3b
   
  urls:
    base_url: https://your-SambaStudio-env.net
    datasets_url: /api/datasets
    projects_url: /api/projects
    jobs_url: /{project_id}/jobs
    download_results_url: /results/download
    
  projects:
    project_name: image_search_project
    project_description: This project will process images batch jobs regarding image search AISK.
  
  jobs:
    job_name: image search job pipeline
    job_description: image search ingestion embedding
    job_task: CLIP
    job_type: batch_predict
    model_checkpoint: CLIP-ViT-B-32-laion2B-s34B-b79k-v2

  output:
    output_path: results/predictions.jsonl