version: '1'
services:
  enterprice_knowledge_retriever_service:
    build: 
      context: ../
      dockerfile: enterprise_knowledge_retriever/docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/enterprise_knowledge_retriever/data